# Generated by Django 5.1.1 on 2024-10-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
